# Generated by Django 3.2.4 on 2022-03-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20220321_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
